### ISSUE TITLE
[Chore] Upgrade to Golang 1.23.4

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-linkerd#586]
#### Current Behavior
Project is running golang 1.21.8.

#### Desired Behavior
Project need updated to golang 1.23.4

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@devhindo fyi

**Comment by devhindo** [comment]
I think `github.com/layer5io/meshkit` needs to be updated first
then `github.com/meshery/meshery-adapter-library` should use the latest version of meshkit after updated
then meshery-linkerd should be updated after that
and only then we upgrade meshery

Reason: there is some compatibilities as the current meshery-linkerd doesn't even compile with the current version of Go due to the incompatable `types.CapabiliyType` which happens because `github.com/meshery/meshery-adapter-library` uses an old version of meshkit `	github.com/layer5io/meshkit v0.6.84` that doesn't have that type.

**Comment by leecalcote** [comment]
@devhindo, yes, I think that you're right. @weilirs, FYI. 

We spoke of this on yesterday's dev meeting.
